package:
  name: cimcb
  version: 0.0.9

source:
  path: ../

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  build:
    - setuptools
    - bokeh 
    - keras
    - numpy 
    - pandas
    - scipy
    - scikit-learn
    - statsmodels
    - python 
    - tensorflow
    - tqdm
    - xlrd

  run:
    - bokeh 
    - keras
    - numpy 
    - pandas
    - scipy
    - scikit-learn
    - statsmodels
    - tensorflow
    - tqdm
    - xlrd

about:
  home: https://github.com/CIMCB
  license: http://www.apache.org/licenses/LICENSE-2.0.html
  summary: "This is a pre-release."
